import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Bucket } from "sst/node/bucket";
import { Amplify } from "aws-amplify";
import config from "./amplifyconfiguration.json";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

Amplify.configure(config);

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://api.tiles.mapbox.com/mapbox-gl-js/v1.4.1/mapbox-gl.css"
          rel="stylesheet"
        />
      </head>
      <body>{children}</body>
    </html>
  );
}
